Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 120 

Metrics/ModuleLength:
  Max: 500

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false 

Style/GuardClause:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/IdenticalConditionalBranches:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Lint/DuplicateMethods:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Max: 100

Metrics/BlockNesting:
  Enabled: false




